# Generated by Django 6.0.5 on 2026-05-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('games', models.CharField(blank=True, help_text='Vergul bilan ajrating: RE2, RE4, RE6', max_length=500, verbose_name="Qatnashgan o'yinlar")),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Personaj',
                'verbose_name_plural': 'Personajlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="O'yin nomi")),
                ('release_year', models.CharField(blank=True, max_length=4, verbose_name='Yil')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('steam_url', models.URLField(blank=True, verbose_name='Steam havolasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='Muqova')),
            ],
            options={
                'verbose_name': "O'yin",
                'verbose_name_plural': "O'yinlar",
                'ordering': ['release_year'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kino nomi')),
                ('release_year', models.CharField(max_length=4, verbose_name='Yil')),
                ('youtube_url', models.URLField(verbose_name='YouTube havolasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='Afisha')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
                'ordering': ['release_year'],
            },
        ),
    ]
