# Generated by Django 6.0.5 on 2026-05-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Masalan: 1967, 1998, 2004', max_length=10, verbose_name='Yil/Sana')),
                ('title', models.CharField(max_length=200, verbose_name='Voqea nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Tarix voqeasi',
                'verbose_name_plural': 'RE Tarixi',
                'ordering': ['year'],
            },
        ),
    ]
